pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index')
]

polls/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('polls/', include('pollster.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pollster/urls.py
from django.urls import path 
from . import views

app_name = 'pollster'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

pollster/models.py
from django.contrib.auth.models import User
from django.utils import timezone
from django.db import models
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Vote(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user}'

    class Meta:
        unique_together = ['choice', 'user']

pollster/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from .models import Question, Choice, Vote
from django.db import IntegrityError
from django.contrib import messages
from django.utils import timezone
from django.urls import reverse

def has_user_already_voted(question, user_id):
    votes = len(Vote.objects.filter(question=question, user_id=user_id))
    return True if votes > 0 else False

@login_required
def index(request):
    latest_question_list = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')
    paginator = Paginator(latest_question_list, 3) 
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'latest_question_list': latest_question_list,
        'page_obj': page_obj
    }
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404('Question does not exist!')
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    voted = has_user_already_voted(question, request.user.id)
    try:
        user_choice = str(Vote.objects.get(question=question, user_id=request.user.id).choice)
    except Vote.DoesNotExist:
        user_choice = None
    labels, data = [], []
    for choice in question.choice_set.all():
        labels.append(choice.choice_text)
        data.append(choice.votes)
    return render(request, 'polls/results.html', {
        'question': question,
        'labels': labels,
        'data': data,
        'user_choice': user_choice,
        'total': sum(data),
        'voted': voted,
    })

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    voted = has_user_already_voted(question, request.user.id)
    try:
        select_choice = question.choice_set.get(pk=request.POST['choice'])
        if voted:
            raise ValueError()
        vote = Vote(choice=select_choice, question=question, user_id=request.user.id)
        vote.save()
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'You did not select a choice.'
        })
    except ValueError:
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'You already voted in this poll.'
        })
    else:
        select_choice.votes += 1
        select_choice.save()
        messages.success(request, f'You have chosen the option: {select_choice.choice_text}')
        return HttpResponseRedirect(reverse('pollster:results', args=(question_id,)))

pollster/templates/polls/detail.html
{% extends 'base.html' %}

{% block title %}{{ question.question_text }}{% endblock %}

{% block content %}
<div class="ui hidden divider"></div>
<a class="black ui button" href="{% url 'pollster:index' %}">Back To Polls</a>
<h1 class="ui header">{{ question.question_text }}</h1>

{% if error_message %}
<p class="ui error message">
    <strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'pollster:vote' question.id %}" method="post">
    {% csrf_token %} 
    <div class="grouped fields">
    {% for choice in question.choice_set.all %}
        <div class="field">
            <div class="ui radio checkbox">
                <input
                    type="radio"
                    name="choice"
                    class="form-check-input"
                    id="choice{{ forloop.counter }}"
                    value="{{ choice.id }}"
                />
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
            </div>
        </div>
    {% endfor %}
    </div>
    <div class="ui divider"></div>
    <input type="submit" value="Vote" class="ui primary button" />
</form>
{% endblock content %}

pollster/templates/polls/index.html
{% extends 'base.html' %} 

{% block content %} 
<h1>Questions</h1>
{% if latest_question_list %}
    {% for question in page_obj %}
    <div class="ui message">
        <p><span class="ui large text">{{ question.question_text }}</span></p>
        <span class="pub-date"><b>Posted:</b> {{ question.pub_date|date:"M d, Y" }}</span>
        {% if question.vote_set.all %}
            <p><b>Voters:</b> {{ question.vote_set.all|join:", " }}</p>
        {% endif %}
        {% if user.username not in question.vote_set.all|join:", " %}
            <a href="{% url 'pollster:detail' question.id %}" class="ui primary button">Vote</a>           
        {% endif %}
        <a href="{% url 'pollster:results' question.id %}" class="ui button">Results</a>      
    </div>
    {% endfor %}
    <div class="ui pagination menu">
        {% if page_obj.has_previous %}
            <a class="item" href="?page=1">&laquo; first</a>
            <a class="item" href="?page={{ page_obj.previous_page_number }}">&laquo; previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="active item" href="?page={{ num }}">{{ num }}</a>    
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}  
                <a class="item" href="?page={{ num }}">{{ num }}</a>     
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="item" href="?page={{ page_obj.next_page_number }}">next &raquo;</a>
            <a class="item" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </div>
{% else %}
    <p>No polls available</p>
{% endif %}
{% endblock content %}

pollster/templates/polls/results.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ question.question_text }}</h1>

<div class="graphic">
    <canvas id="pie-chart"></canvas>
</div>

{% if user_choice %}
    <p>You have chosen the option: <b>{{ user_choice }}</b></p>
{% else %}
    <p>You haven't voted yet in this poll</p>
{% endif %}

<div class="ui middle aligned divided list">
    {% for choice in question.choice_set.all %}
    <div class="item {% if user_choice == choice.choice_text %}voted{% endif %}">
        <div class="right floated content">
            <div class="ui label">{{ choice.votes }} vote{{ choice.votes | pluralize }}</div>
        </div>
        <div class="content">
            <p><span class="ui large text">{{ choice.choice_text }}</span></p>
        </div>
    </div>
    {% endfor %}
    <div class="item total">
        <div class="right floated content">
            <div class="ui label">{{ total }} vote{{ total | pluralize }}</div>
        </div>
        <div class="content">
            <p><span class="ui large text">Total Votes</span></p>
        </div>
    </div>
</div>

<a class="black ui button" href="{% url 'pollster:index' %}">Back To Polls</a>
{% if not voted %}
    <a class="ui primary button" href="{% url 'pollster:detail' question.id %}">Vote</a>
{% endif %}

<script>
var config = {
    type: 'pie',
    data: {
        datasets: [{
            data: {{ data|safe }},
            backgroundColor: [
                '#bf0820', '#1a0eb5', '#04b020', '#b09f04', '#db6504', '#04c4c1', '#5804c7'
            ],
        }],
            labels: {{ labels|safe }}
        },
    options: {
        responsive: true,
        maintainAspectRatio: false
    }
};

window.onload = function() {
    var ctx = document.getElementById('pie-chart').getContext('2d');
    var canvas = document.getElementById('pie-chart')
    window.myPie = new Chart(ctx, config);
    var polls = config.data.datasets[0].data.length;
    var zeros = []
    for (var i = 0; i < polls; i++) {
        if (config.data.datasets[0].data[i] == 0) {
            zeros.push(config.data.datasets[0].data[i])
        }
    }
    if (polls == zeros.length) {
        canvas.style.display = 'none';
    }
};
</script>
{% endblock content %}